### ISSUE TITLE
Slim-lint warning: 2.5.6-compliant syntax, but you are running 2.5.1.

### ISSUE THREAD

**Issue by letuduykhanh** [sds/slim-lint#103]
slim-lint app/views/contact_mailer/notification.html.slim
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.6-compliant syntax, but you are running 2.5.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
no implicit conversion of String into Integer
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration.rb:104:in `block (2 levels) in ensure_linter_include_exclude_arrays_exist'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration.rb:102:in `each'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration.rb:102:in `block in ensure_linter_include_exclude_arrays_exist'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration.rb:101:in `each_key'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration.rb:101:in `ensure_linter_include_exclude_arrays_exist'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration.rb:85:in `validate'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration.rb:19:in `initialize'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration_loader.rb:70:in `new'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration_loader.rb:70:in `load_from_file'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration_loader.rb:36:in `load_file'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/configuration_loader.rb:20:in `load_applicable_config'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/runner.rb:42:in `load_applicable_config'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/runner.rb:17:in `run'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/cli.rb:84:in `scan_for_lints'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/cli.rb:53:in `act_on_options'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/lib/slim_lint/cli.rb:25:in `run'
/Users/mrk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/slim_lint-0.17.1/bin/slim-lint:7:in `<top (required)>'
/Users/mrk/.rbenv/versions/2.5.1/bin/slim-lint:23:in `load'
/Users/mrk/.rbenv/versions/2.5.1/bin/slim-lint:23:in `<main>'
Report this bug at https://github.com/sds/slim-lint/issues

To help fix this issue, please include:
- The above stack trace
- Slim-Lint version: 0.17.1
- RuboCop version: 0.74.0
- Ruby version: 2.5.1

I have tried with ruby 2.6.2, still have the same warning.

**Comment by sds** [comment]
The warning text is from RuboCop (specifically the `parser` gem it uses), and is not likely to be related to this issue.

Can you provide the content of `app/views/contact_mailer/notification.html.slim`, or a trimmed down version that still reproduces the issue?

Can you also include your `.slim-lint.yml` file?

**Comment by letuduykhanh** [comment]
I'm using your default config for `.slim-lint.yml`,  and `app/views/contact_mailer/notification.html.slim` only has `p A`.

**Comment by sds** [comment]
I can't reproduce. 

When you say you're using the default configuration, does that mean you don't have a `.slim-lint.yml` file? Or does it mean you copied [`config/default.yml`](https://github.com/sds/slim-lint/blob/fd6dd9afb73dd2de2e5af4b4b795afa8af09b8eb/config/default.yml) into your repository's local `.slim-lint.yml`?

I tried both and was unable to reproduce this issue. Are you sure you did a straight-up copy? Your configuration file may just be malformed.

**Comment by letuduykhanh** [comment]
Yes, I did a straight-up copy `config/default.yml` and renamed to `.slim-lint.yml`. Thanks anyway.
