### ISSUE TITLE
Is there a Rubocop plugin?

### ISSUE THREAD

**Issue by shime** [sds/slim-lint#106]
Thank you for creating this project.

I'd like to integrate this tool with Rubocop, in order to have slim linting in one command: `rubocop`. 

Is there a way to do so?

**Comment by sds** [comment]
I'm not aware of one, or how to build such support. If you figure out how, happy to accept a pull request if changes need to be made to this repository.

However, I imagine this would be a separate repository that RuboCop includes as a plugin, so you are welcome to build that yourself.
