### ISSUE TITLE
Is there a way to inherit .slim-lint.yml files?

### ISSUE THREAD

**Issue by themilkman** [sds/slim-lint#114]
Hi, first of all: thanks for this project!

Maybe I'd overlooked (sorry in that case) it but is there a way to inherit linter config file? Like the rubocop:

```
 inherit_from:
   - 'my/path/to/a/shared/submodule_repo/.rubocop.yml'
```

config? Since I work on multiple projects this would be very helpful for me.

Thanks for any response.

**Comment by sds** [comment]
Hey @themilkman, there is not currently a way to inherit configuration files with Slim-Lint.

I'm going to close this issue as answered, but feel free to open a PR if this is functionality you'd like to see. Thanks!
