### ISSUE TITLE
Rubocop: ignored_cops are not ignored

### ISSUE THREAD

**Issue by enthusiasmus** [sds/slim-lint#115]
Hi!

When running slim-lint, the [default config](https://github.com/sds/slim-lint/blob/master/config/default.yml) seems not be used at all.

```
➜  git:(xxx) ✗ slim-lint --verbose-version                                                 
slim-lint 0.20.0
slim 4.0.1
rubocop 0.80.1
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```

```
➜  git:(xxx) ✗ slim-lint app/views/products/_product_tile.html.slim   
app/views/products/_product_tile.html.slim:48 [W] RuboCop: Style/IdenticalConditionalBranches: Move `render "products/product_tile/standard", small_layout: small_layout` out of the conditional.
app/views/products/_product_tile.html.slim:56 [W] RuboCop: Style/IdenticalConditionalBranches: Move `render "spree/products/product_tile/standard", small_layout: small_layout` out of the conditional.
```

The `Style/IdenticalConditionalBranches` should be ignored, but it isn't. What do I miss? I also tried with a .slim-lint.yml and also with explicit usage via `slim-lint -c .slim-lint.yml`.

Thanks in advance!
Best regards

**Comment by sds** [comment]
If `Style/IdenticalConditionalBranches` was the only cop appearing, it's because we haven't released a gem version with #113 included.

[0.20.1](https://github.com/sds/slim-lint/releases/tag/v0.20.1) has been released.

**Comment by enthusiasmus** [comment]
Awesome! Thank you!

Now the exclusion for the `Style/IdenticalConditionalBranches` works by default!

When I want to add an other cop the ignore list, than it still doesn't work:

```
➜   git:(xxx) ✗ slim-lint --verbose-version                                                 
slim-lint 0.20.1
slim 4.0.1
rubocop 0.80.1
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```

```
➜  git:(xxx) ✗ slim-lint app/views/spree/products/_product_tile.html.slim -c .slim-lint.yml
app/views/products/_product_tile.html.slim:50 [W] RuboCop: Lint/DuplicateHashKey: Duplicated key in hash literal.
app/views/products/_product_tile.html.slim:58 [W] RuboCop: Lint/DuplicateHashKey: Duplicated key in hash literal.
```

.slim-lint.yml
```
linters:
  LineLength:
    enabled: true
    max: 100

  Rubocop:
    enabled: true
    ignored_cops:
      - Lint/DuplicateHashKey
```

**Expected behaviour:** slim-lint should use the .slim-lint.yml and don't report the `Lint/DuplicateHashKey` offenses and report the `Style/IdenticalConditionalBranches` offenses (because I overwrote the default.yml).

Best regards

**Comment by enthusiasmus** [comment]
Found it... RuboCop instead of Rubocop. My bad!
