### ISSUE TITLE
Question: Inline configuration, a la RuboCop?

### ISSUE THREAD

**Issue by jdickey** [sds/slim-lint#116]
Given that I have the following as part of a Slim template (for Hanami, not that it should matter):

```slim
doctype html
html lang="en"
  head
    meta charset="UTF-8"
    title
      | FooBarBaz Web
    link [href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.1/normalize.css"
          rel="stylesheet"] /
    link [crossorigin="anonymous"
          href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          rel="stylesheet"] /
    / ...
```

The second-to-last line (which begins with `integrithy=`) is more than 80 characters long. I know I could simply set a maximum `LineLength` in `.slim-lint.yml` that would cover iot and go on. I know I could even limit that override to just that one file by using the `Include` entry below `LineLength`, specifying just that one file. *If I was confident that that one file was the only file that would need such overriding,* that would be just fine. If I were satisfied to simply set a `LineLength` override sufficient for *all* such files, I'd be just fine then, too.

That last in particular, though, is likely to be an increasingly big ask over the life of the project. What I (and, I suppose, many others) could really *use* would be an inline config override, something like

```slim
    link [href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.1/normalize.css"
          rel="stylesheet"] /
    / slim-lint:disable LineLength
    link [crossorigin="anonymous"
          href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          rel="stylesheet"] /
    / slim-lint:enable LineLength
    / ...
```

That would have major benefits:

1. It would make it explicit to anyone reading the file that I know the code between the comments fails the specified lint check; and
2. It does *not* force me to either guesstimate or continually revise a one-length-fits-all override for all non-compliant lines in all files within my project.

I'm surprised that this sort of thing apparently hasn't come up for discussion before but, after making a (somewhat quick) reading of the (open and closed) issues, and the source code, and checking StackOverflow (because why not), I haven't been able to find anything.

Thoughts? Or am I missing something blindingly obvious to the rest of the developer and tool-using communities?

**Comment by sds** [comment]
Completely open to (and supportive of) the suggestion! A pull request would be most welcome.

**Comment by dkniffin** [comment]
I would also love to see this feature added to slim-lint. I don't have the time to make a PR, but I did do some initial digging into how Rubocop does this and found [this class](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/comment_config.rb) that does part of the work

**Comment by dkniffin** [comment]
While digging in a bit more to determine how this would be done, I found it this _is_ currently possible for RuboCop cops by doing:

```slim
- # rubocop:disable Rails/OutputSafety
p = raw(@blog.content)
- # rubocop:enable Rails/OutputSafety
```

There's a spec for that here: https://github.com/dkniffin/slim-lint/blob/master/spec/slim_lint/linter/comment_control_statement_spec.rb#L26

**Comment by dkniffin** [comment]
Pull request created! #129 @sds
