### ISSUE TITLE
Disable via source

### ISSUE THREAD

**Issue by afestein** [sds/slim-lint#12]
Loving this. Would be great we could [disable linters via source](https://github.com/brigade/scss-lint#disabling-linters-via-source) to have nice granular control as in scss-lint.

e.g. `// slim-lint:disable LineLength`

**Comment by sds** [comment]
Totally agree that this would be awesome to have. Will get to it when I can, otherwise a pull request would be most welcome!

**Comment by borama** [comment]
I believe that this issue has already been addressed in #129.
