### ISSUE TITLE
Question: Multi-line Methods and RuboCop Layout/FirstArgumentIndentation

### ISSUE THREAD

**Issue by nickbayley** [sds/slim-lint#122]
Hey.

I will often split long method calls onto multiple lines. I usually do it like below:

```
= text_field_tag( \
  'passwordless[email]', params.fetch('passwordless[email]', nil),
  class: 'uppercase font-bold tracking-widest' \
)
```

This gives me the following error when I run slim-lint on it:

`[W] RuboCop: Layout/FirstArgumentIndentation: Indent the first argument one step more than the start of the previous line.`

Is this another one that needs to be added to the default exclude list? Or am I doing something wrong?

Thanks.

**Comment by ibrahima** [comment]
I am also wondering about this, I can't find an indentation that it accepts... I imagine that because the Ruby code is extracted out before passing to rubocop the indentation information might be lost somehow.
