### ISSUE TITLE
Unsupported new rubocop cop `Layout/LineEndStringConcatenationIndentation`

### ISSUE THREAD

**Issue by marcelolx** [sds/slim-lint#132]
The new cop introduced here https://github.com/rubocop/rubocop/pull/9883 seems to not work well with slim-lint, for now, we disabled it in our config file, but maybe it should be included in the config file with the other cops? https://github.com/sds/slim-lint/blob/master/config/default.yml#L48

**Comment by sds** [comment]
@marcelolx Can you confirm which version of Slim Lint you are using? This is addressed as of [0.22.0](https://github.com/sds/slim-lint/releases/tag/v0.22.0) thanks to #130.

I will close this as resolved. Let me know if I misunderstood.

**Comment by marcelolx** [comment]
@sds Sorry, the problem is that we've our own `.slim-lint.yml` file and I didn't check if it was present in the slim-lint `default.yml`, my fault.
