### ISSUE TITLE
silence parser warnings after ruby upgrade

### ISSUE THREAD

**Issue by phoet** [sds/slim-lint#143]
just upgraded to ruby 3.1.3 and slim-lint was issuing a warning:

> warning: parser/current is loading parser/ruby31, which recognizes3.1.2-compliant syntax, but you are running 3.1.3.
> Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

the link in the warning is not super helpful in regards to what's going on here or what to do with slim-lint, if anything needs to be done at all.

i'm using slim-lint extension for vs code on save, so this is quite distracting to have that message on save. it seems it can be fixed by `gem install parser` to latest dependency.

rubocop is just silencing those warnings:
https://github.com/marcandre/rubocop-ast/commit/7081f7cae0326150b648c54a99e124998ab2bffb

**Comment by sds** [comment]
Fixed in [0.24.0](https://github.com/sds/slim-lint/releases/tag/v0.24.0). Thanks!
