### ISSUE TITLE
Require is very slow.

### ISSUE THREAD

**Issue by yxhuvud** [sds/slim-lint#148]
Requiring slim_lint take over 200ms on my machine. That is a full fifth of the starting time of the rails app I'm working on, and a factor 5 longer than mime-types which is the second worst. What is it doing that make it take so much time?

**Comment by sds** [comment]
It's the dependency on RuboCop.

```
⨠ ruby -e "require 'benchmark'; time = Benchmark.measure { require 'rubocop' }; puts time.real" 2>/dev/null
0.374636999797076
```

```
⨠ ruby -e "require 'benchmark'; time = Benchmark.measure { require 'slim_lint' }; puts time.real" 2>/dev/null
0.4574480000883341
```

There's no reason you should be running a linter as part of your Rails app. You can use [Bundler groups](https://bundler.io/guides/groups.html) to separate CI-only dependencies from required runtime ones so you don't incur the load delay every time you start the app.
