### ISSUE TITLE
simple_form templates

### ISSUE THREAD

**Issue by justin808** [sds/slim-lint#2]
https://github.com/plataformatec/simple_form/issues/1100

Any way to avoid directories like lib/templates/slim/scaffold?

Note, this does not happen with the rake task.

I ran this like

```
slim-lint app/**/*.slim
```

```
./lib/templates/slim/scaffold/_form.html.slim:1 [W] RuboCop: Syntax: unexpected `@'
```

Here's the file:

```
= simple_form_for(@<%= singular_table_name %>) do |f|
  = f.error_notification

  .form-inputs
<%- attributes.each do |attribute| -%>
    = f.<%= attribute.reference? ? :association : :input %> :<%= attribute.name %>
<%- end -%>

  .form-actions
    = f.button :submit
```

**BTW -- LOOKS AWESOME!**

**Comment by sds** [comment]
Hey @justin808, thanks for the feedback.

I've added support for a global `exclude` option in your `.slim-lint.yml` which can take a list of file or glob patterns and excludes any matching files from all linters.

You can now also include/exclude files on a per-linter basis. See the [README](https://github.com/sds/slim-lint#linter-options) for details.

**Comment by samnang** [comment]
@sds it still doesn't work and gets the same message. Here is what I tried in `.slim-lint.yml`

```
exclude:
  - 'lib/templates/slim/scaffold/_form.html.slim'
```

**Comment by sds** [comment]
Hey @samnang,

Your exclusion wasn't getting matched because it didn't have a leading `./`, i.e.

```yaml
exclude:
  - './lib/templates/slim/scaffold/_form.html.slim'
```

This is not obvious so I've fixed the behavior to work regardless of whether `./` is present or not in edf3f55c370daf5eb21a0992d9b2a574fbc10900. 

Thanks for the report!
