### ISSUE TITLE
Display wrong line number

### ISSUE THREAD

**Issue by opodartho** [sds/slim-lint#37]
Slim-lint display wrong line number for errors when ruby code is written in multiple lines. If ruby code break down into multiple line then slim-lint should count this as multiple line not one line.

Here is a screenshot:
[Screenshot](https://dl.dropboxusercontent.com/u/72140384/Screenshot%20from%202016-06-26%2016-51-37.png)

Redundant div is in line 19 but error displaying in line 15.

**Comment by sds** [comment]
Thanks for the report!

Fixed in #38.
