### ISSUE TITLE
ancient browser check file

### ISSUE THREAD

**Issue by justin808** [sds/slim-lint#4]
```
app/views/layouts/application/_ancient_browser_check.html.slim:2 [W] LineLength: Line is too long. [260/120]
```

Here's the file
```
/ noinspection LineLength
/![if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p
```

What do you recommend?

**Comment by sds** [comment]
Hey @justin808,

Can you not just split up your code across multiple lines to avoid the line length issue? Also, is there a reason you're not using Slim for this part of the code? According to the [Slim documentation](http://www.rubydoc.info/gems/slim/frames#IE_conditional_comment_______), you should be able to nest Slim code under the IE conditional comment, e.g.

```slim
/![if lt IE 7]
  p.chromeframe 
    Your browser is <em>ancient!</em>
    a href="http://browsehappy.com/" Upgrade your browser
    ...
```

**Comment by justin808** [comment]
@sds That looks great. We'll try this out. CC: @ben-ward.
