### ISSUE TITLE
Better flycheck support

### ISSUE THREAD

**Issue by jtdowney** [sds/slim-lint#50]
I opened flycheck/flycheck#1102 because I noticed that Flycheck+Slim-lint was not respecting the `.rubycop.yml` in my projects main folder. This stems from flycheck copying the file to be linted to a temp folder. I suspect it would also not respect the `.slim-lint.yml` but that is easily fixed by passing the path to it with `--config`.

I read through the code and found there is a way to pass the path of the rubocop config through an environment variable, but I am told that flycheck does not support this currently. There are a couple of different solutions to this as I see it:

1. Allow slim-lint to take the source from STDIN and pass a flag to override the file path, this seems to be preferred by flycheck according to flycheck/flycheck#1102.
2. Add flag to slim-lint to accept rubocop config path on the command line.
3. Something I haven't thought of yet

I wanted to open an issue first to start a conversation instead of just dropping a PR. What would be preferred from the slim-lint side? I am happy to take a stab at a PR, just wanted to get some insight first.

**Comment by sds** [comment]
Hey @jtdowney, thanks for bringing this up.

I've been meaning to refactor `slim-lint` to use the [Lint Trappings](https://github.com/sds/lint-trappings) framework, which has built-in support for passing files via STDIN. Unfortunately, the migration introduces a number of breaking changes, but I think the benefits are worth it.

I already have a branch in progress, but am swamped at the moment. However, if you provide a pull request adding support for the `--stdin-file-path` flag, I'll be happy to merge it. Thanks!

**Comment by sds** [comment]
Implemented the `--stdin-file-path` in #125 and released in [Slim-Lint `0.21.0`](https://rubygems.org/gems/slim_lint).
