### ISSUE TITLE
New Editor Integration for Atom

### ISSUE THREAD

**Issue by mattaschmann** [sds/slim-lint#51]
I've take the liberty of creating an atom linter plugin for your excellent tool, as I noticed one did not yet exist.  The repo is https://github.com/mattaschmann/linter-slim-lint if you think it's worth adding to the applicable section in your readme.

**Comment by sds** [comment]
Thanks for building the integration, @mattaschmann!

Added some documentation in c4da51a3d5de781ecf0c5c2945739499d69f1f4c.
