### ISSUE TITLE
In-memory file analysis

### ISSUE THREAD

**Issue by tagliala** [sds/slim-lint#69]
Hi,

I've noticed that slim-lint is creating a .rb file in the same folder of the file to inspect (which causes git clients to continuously see new files).

Is there any chance of doing this in memory or using stdoutput or at worst in a temporary dir like application's /tmp?

Thanks

**Comment by sds** [comment]
Hey @tagliala, a similar request was asked for HAML-Lint, and someone went ahead and submitted a [PR for it](https://github.com/brigade/haml-lint/pull/172).

I am happy to merge a PR adding support. Thanks!
