### ISSUE TITLE
Slim-lint 0.11-0.13 are broken for RuboCop 0.50.0 or newer

### ISSUE THREAD

**Issue by Ana06** [sds/slim-lint#75]
Slim-lint 0.11-0.13 are broken for RuboCop 0.50.0 or newer. This should be documented somewhere.

In general it may be a good practise to have `s.add_dependency 'rubocop', '~> 0.50.0'` and `s.add_dependency 'rubocop', '>= 0.50.0'` if a Rubocop update may break a slim-lint in the [slim_lint.gemspec](https://github.com/sds/slim-lint/blob/master/slim_lint.gemspec).

**Comment by sds** [comment]
Newer versions of Slim-Lint are fixed. In general, RuboCop is pretty good about not releasing breakages, and it's probably too constraining to apply `~> 0.50.0` as RuboCop usually releases at a faster rate than Slim-Lint, and I'd rather not need to release "catch up" releases of Slim-Lint which only change the dependency.
