### ISSUE TITLE
"Style/IdenticalConditionalBranches: Move `something` out of the conditional" is wrong interpreted.

### ISSUE THREAD

**Issue by LionelLindt** [sds/slim-lint#99]
If I have this code for example:
```
- if condition?
    a[target='_blank' href='#'] = name
- else
  = name
```
Slim would now report this error two times:
```
[W] RuboCop: Style/IdenticalConditionalBranches: Move `name` out of the conditional.
```
[Here](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/IdenticalConditionalBranches) is the logic behind it' s report.

But unfortunately in this case it is not possible to move `name` out of the condition, because either the name of the link would be equal to `name` or something on above the condition (for example a `p` tag).
I am aware that I could've used the rails `link_to` method and the problem wouldn't have appeared. The usage of the `a` tag here is just to demonstrate my point.

I expect slim to recognise when the element used, in both the `if` and the `else` block, is called in void context or assigned to something.

**Comment by wenbo** [comment]
@LionelLindt 
I'm also conflicted with this issue. so I want to know how do you overcome it.
